version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "~/project/backend/package.json" }}{{checksum "~/project/frontend/package.json"}}

          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd ~/project/backend && yarn install
      - run: cd ~/project/frontend && yarn install

      - save_cache:
          paths:
            - ~/project/backend/node_modules
            - ~/project/frontend/node_modules
          key: dependencies-{{ checksum "~/project/backend/package.json" }}{{checksum "~/project/frontend/package.json"}}
        
      # run tests!
      - run: cd ~/project/backend && yarn test_server